// Fetches REAL price history from Yahoo Finance (no API key) and bakes it
// into lib/data/static/*.json + registry.ts. Run with: npm run gen:data
// Candle granularity is per range (intraday for short ranges — see RANGE_INTERVAL)
// so every timeframe builds a full-length terrain. This is the only data source —
// terrain always reflects actual market moves.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ASSETS, metaOf } from '../lib/data/assets.ts';
import { RANGE_INTERVAL, RANGE_POINTS, RANGES, type ChartSeries, type PricePoint, type Range } from '../lib/data/types.ts';

const here = dirname(fileURLToPath(import.meta.url));
const staticDir = join(here, '..', 'lib', 'data', 'static');
mkdirSync(staticDir, { recursive: true });

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36';

// Yahoo range token per app Range.
const YRANGE: Record<Range, string> = { '1M': '1mo', '6M': '6mo', '1Y': '1y', '5Y': '5y' };

// App symbol -> Yahoo ticker.
function yahooSymbol(symbol: string, cls: string): string {
  if (cls === 'crypto') return `${symbol}-USD`;
  if (cls === 'india') return `${symbol}.NS`;
  return symbol;
}

// Evenly downsample to the target terrain point count for a range.
function downsample(points: PricePoint[], range: Range): PricePoint[] {
  const target = RANGE_POINTS[range];
  if (points.length <= target) return points;
  const out: PricePoint[] = [];
  const step = (points.length - 1) / (target - 1);
  for (let i = 0; i < target; i++) out.push(points[Math.round(i * step)]);
  return out;
}

type YahooResp = {
  chart?: {
    result?: {
      timestamp?: number[];
      indicators?: { quote?: { close?: (number | null)[] }[] };
    }[];
    error?: unknown;
  };
};

async function fetchSeries(yhSymbol: string, range: Range): Promise<PricePoint[]> {
  const url =
    `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(yhSymbol)}` +
    `?range=${YRANGE[range]}&interval=${RANGE_INTERVAL[range]}`;
  const res = await fetch(url, { headers: { 'User-Agent': UA, accept: 'application/json' } });
  if (!res.ok) throw new Error(`yahoo ${yhSymbol} ${range}: HTTP ${res.status}`);
  const json = (await res.json()) as YahooResp;
  const r = json.chart?.result?.[0];
  const ts = r?.timestamp;
  const closes = r?.indicators?.quote?.[0]?.close;
  if (!ts || !closes) throw new Error(`yahoo ${yhSymbol} ${range}: empty`);

  const pts: PricePoint[] = [];
  for (let i = 0; i < ts.length; i++) {
    const c = closes[i];
    if (c == null || !Number.isFinite(c)) continue; // skip gaps/holidays
    pts.push({ t: ts[i] * 1000, close: Math.round(c * 100) / 100 });
  }
  if (pts.length < 5) throw new Error(`yahoo ${yhSymbol} ${range}: too few points`);
  return pts;
}

async function main() {
  const keys: string[] = [];

  for (const profile of ASSETS) {
    for (const range of RANGES) {
      const yh = yahooSymbol(profile.symbol, profile.class);
      const raw = await fetchSeries(yh, range);
      const points = downsample(raw, range);
      const series: ChartSeries = { meta: metaOf(profile), range, points, live: false };
      const key = `${profile.symbol}_${range}`;
      keys.push(key);
      writeFileSync(join(staticDir, `${key}.json`), JSON.stringify(series));
      console.log(`  ${key}: ${points.length} pts  (${yh})`);
      // Be polite to Yahoo between requests.
      await new Promise((r) => setTimeout(r, 350));
    }
  }

  const imports = keys.map((k) => `import ${k} from './${k}.json';`).join('\n');
  const entries = keys.map((k) => `  '${k}': ${k} as ChartSeries,`).join('\n');
  const registry = `// AUTO-GENERATED by scripts/fetch-real-data.mts — do not edit by hand.
import type { ChartSeries } from '../types';
${imports}

export const STATIC_SERIES: Record<string, ChartSeries> = {
${entries}
};
`;
  writeFileSync(join(staticDir, 'registry.ts'), registry);
  console.log(`\nWrote ${keys.length} REAL series + registry.ts to lib/data/static/`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
