// Regenerates the bundled illustrative chart data. Run with: npm run gen:data
// Writes one JSON file per asset+range plus a static registry.ts so the bundler
// can statically include every series (no dynamic-import context needed).
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateAll } from '../lib/data/generate.ts';

const here = dirname(fileURLToPath(import.meta.url));
const staticDir = join(here, '..', 'lib', 'data', 'static');
mkdirSync(staticDir, { recursive: true });

const series = generateAll();
const keys: string[] = [];

for (const s of series) {
  const key = `${s.meta.symbol}_${s.range}`;
  keys.push(key);
  writeFileSync(join(staticDir, `${key}.json`), JSON.stringify(s));
}

// Build a typed registry that statically imports every JSON file.
const imports = keys.map((k) => `import ${k} from './${k}.json';`).join('\n');
const entries = keys.map((k) => `  '${k}': ${k} as ChartSeries,`).join('\n');
const registry = `// AUTO-GENERATED by scripts/gen-data.mts — do not edit by hand.
import type { ChartSeries } from '../types';
${imports}

export const STATIC_SERIES: Record<string, ChartSeries> = {
${entries}
};
`;
writeFileSync(join(staticDir, 'registry.ts'), registry);

console.log(`Wrote ${keys.length} series + registry.ts to lib/data/static/`);
